name: appser
description: "A new Flutter project."
publish_to: 'none'
version: 0.6.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  just_audio: ^0.9.40
  video_player: ^2.9.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  chewie: ^1.8.5
  shared_preferences: ^2.3.2
  http: ^1.2.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png" 

flutter:
  uses-material-design: true
    
  assets:
    - assets/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
